config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import (
    StudentDashboardView, StudentGroupView, StudentLessonsView, 
    HomeworkView, HomeDetailView, ProfileView, EditProfileView, 
    ResetPasswordView,HomeworkListView
)

app_name = 'students'
urlpatterns = [
    path('dashboard/', StudentDashboardView.as_view(), name='dashboard'),
    path('groups/', StudentGroupView.as_view(), name='groups'),
    path('resed_password/', ResetPasswordView.as_view(), name='resed_password'),
    path('profil-students/', ProfileView.as_view(), name='profil'),
    path('lessons/<int:group_id>/', StudentLessonsView.as_view(), name='lessons'),
    path('homework/<int:lesson_id>/', HomeworkView.as_view(), name='homework'),
    path('edit/<int:id>/', EditProfileView.as_view(), name='edit'),
    path('homework-detail/<int:lesson_id>/', HomeDetailView.as_view(), name='homework_detail'),
    path('homeworks/<int:lesson_id>/', HomeworkListView.as_view(), name='homework_list'),
  ]

users/urls.py
from django.urls import path
from .views import (LoginView, RegisterView,ProfileView,EditProfileView,Create,TeamStudentListView,
                    LogautView,GroupsView,StudentView,EditStudentView,Delete,StudentByTeam,
                    ResetPasswordView,AdminDashboardView,CreateTeamView,DeleteTeamView)

app_name = 'users'


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogautView.as_view(), name='logout'),
    path('create/', Create.as_view(), name='create'),
    path('profil/', ProfileView.as_view(), name='profil'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('edit/<int:id>/', EditProfileView.as_view(), name='edit'),
    path('group/', GroupsView.as_view(), name='groups'),
    path('students/', StudentView.as_view(), name='students'),
    path('get-by-students/<int:id>/', StudentByTeam.as_view(), name='students_by'),
    path('edit-student/<int:id>/', EditStudentView.as_view(), name='edit_student'),
    path('delete/<int:id>/', Delete.as_view(), name='delete'),
    path('resed-password', ResetPasswordView.as_view(), name='resed_password'),
    path('create-team/', CreateTeamView.as_view(), name='create_team'),
    path('delete-team/<int:id>/', DeleteTeamView.as_view(), name='delete_team'),
    path('team/student/create/', TeamStudentListView.as_view(), name='create_student'),
]

students/models.py
from django.db import models
from users.models import Team,Student,Teacher
from django.core.validators import MaxValueValidator,FileExtensionValidator

class Lesson(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='lesson')
    title = models.CharField(max_length=100, unique=True)
    date = models.DateField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    homework_status = models.BooleanField(default=False)
    lesson_file = models.FileField(upload_to='lesson/',  null=True,blank=True)
    video = models.FileField(
        upload_to='video/', 
        validators=[FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'AVI', 'WMV'])],
        null=True,
        blank=True
    )


    class Meta:
        unique_together = ['team', 'title']

    def __str__(self):
        return self.title


class Homework(models.Model):
    lesson = models.OneToOneField(Lesson, on_delete=models.CASCADE, related_name='homework')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, related_name='homeworks')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='students')
    description = models.TextField()
    homework_file = models.FileField(upload_to='homeworks', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)


    class Meta:
        unique_together = ['student', 'team']

    def __str__(self):
        return f"{self.student.user.first_name}-- {self.lesson.title}"

class Davomat(models.Model):
    team = models.ForeignKey(Team,on_delete=models.CASCADE,related_name='team',null=True,blank=True)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.student} --> ,{self.data} --> {'Present' if self.status else 'Absent'}"
    

students/forms.py
from django import forms
from .models import Homework,Davomat

class HomeworkForm(forms.Form):
    description = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))
    homework_file = forms.FileField(widget=forms.FileInput())


class DavomatForm(forms.ModelForm):
    class Meta:
        model = Davomat
        fields = ['team', 'student', 'status'] 
        widgets = {
            'team': forms.Select(attrs={'class': 'form-control'}),
            'student': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from users.permissionmixin import StudentRequiredMixin
from django.views import View
from users.models import Student, Team,User
from .forms import HomeworkForm,DavomatForm
from .models import Lesson, Homework,Davomat
from users.forms import ProfileForm,ResetPasswordForm

class StudentDashboardView(StudentRequiredMixin, View):
    def get(self, request):
        return render(request, 'students/dashboard.html')

class StudentGroupView(StudentRequiredMixin, View):
    def get(self, request):
        student = Student.objects.get(user=request.user)
        return render(request, 'students/guruhlarim.html', context={"student":student})
    
class HomeworkListView(View):
    def get(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        homeworks = Homework.objects.filter(lesson=lesson)
        return render(request, 'students/homework.html', {'lesson': lesson, 'homeworks': homeworks})

class StudentLessonsView(StudentRequiredMixin, View):
    def get(self, request, group_id):
        team = get_object_or_404(Team, id=group_id)
        lessons = team.lesson.all()
        return render(request, 'students/lessons.html', context={"lessons":lessons})
    

class HomeworkView(StudentRequiredMixin, View):
    def get(self, request, lesson_id):
        form = HomeworkForm()
        return render(request, 'students/homework.html', context={"form":form})
    
    def post(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        student = get_object_or_404(Student, user=request.user)

        form = HomeworkForm(request.POST, request.FILES)
        if form.is_valid():
            homework = Homework()
            homework.lesson = lesson
            homework.student = student
            homework.description = form.cleaned_data['description']
            homework.homework_file = form.cleaned_data['homework_file']
            homework.save()

            lesson.homework_status = True
            lesson.save()

            return redirect('students:dashboard')
        form = HomeworkForm()
        return render(request, 'students/homework.html', context={"form":form})
        
class HomeDetailView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        student = get_object_or_404(Student , user=request.user)
        homework = Homework.objects.filter(lesson=lesson , student=student).first()
        return render(request,'students/homedetail.html',{'homework':homework})
    
class ProfileView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        return render(request,'students/profil.html',context={"user":user})


class EditProfileView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(instance=user)
        return render(request, 'students/edit.html', {'form': form})

    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('students:profil')  
        return render(request, 'students/edit.html', {'form': form})

class ResetPasswordView(LoginRequiredMixin,View):
    def get(self, request):
        form = ResetPasswordForm()
        return render(request, 'students/reset_password.html', {'form':form})

    def post(self, request):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            user = request.user
            user.set_password(new_password)
            user.save()
            return redirect('/')
        form = ResetPasswordForm()
        return render(request, 'students/reset_password.html', {'form':form})
    
class DavomatListView(View):
    def get(self, request):
        davomat_list = Davomat.objects.all()
        form = DavomatForm()
        return render(request, 'students/davomat_list.html', {'davomat_list': davomat_list, 'form': form})

    def post(self, request):
        form = DavomatForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('davomat_list')
        davomat_list = Davomat.objects.all()
        return render(request, 'students/davomat_list.html', {'davomat_list': davomat_list, 'form': form})

students/templates/students/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Offline Student Panel</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="icon" href="{% static 'icon/talim.ico' %}">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.min.css"
    rel="stylesheet"
    />
</head>
<body style="background-color: rgb(237, 243, 245)">
    <!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="background-color: rgb(250, 248, 244);">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">

                <a
                    href="{% url 'students:dashboard' %}"
                    class="list-group-item list-group-item-action py-2 ripple"
                    aria-current="true"
                >
                    <i class="fas fa-globe fa-fw me-3"></i><span>Bosh sahifa</span>
                </a>

          <a href="#" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-money-bill fa-fw me-3"></i><span>To'lovlarim</span>
          </a>

          <a href="{% url 'students:groups' %}" class="list-group-item list-group-item-action py-3 ripple"
            ><i class="fas fa-users fa-fw me-4"></i><span>Guruhlarim</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-line fa-fw me-3"></i><span>Ko'rsatgichlarim</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-chart-pie fa-fw me-3"></i><span>Reyting</span>
          </a>
          <a href="{% url 'students:profil' %}" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-bar fa-fw me-3"></i><span>Sozlamalar</span></a
          >
        </div>
      </div>
    </nav>
    <!-- Sidebar -->
  
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button data-mdb-button-init
          class="navbar-toggler"
          type="button"
          data-mdb-collapse-init
          data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
  
        <!-- Brand -->
        <a class="navbar-brand" href="#">
        <img
          src="{% static 'icon/ummat.jpg' %}"
          height="50"
          alt="ummat ta`lim Logo"
          loading="lazy"
        />
        </a>
      </a>
  
        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">
            <!-- Avatar -->
          <li class="nav-item dropdown" style="background-color: rgb(250, 248, 246);">
            <a
              data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="{{ user.image.url }}"
                class="rounded-circle"
                height="22"
                alt="Avatar"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <li>
                <a class="dropdown-item" href="{% url 'users:profil' %}">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->
 
  <!--Main layout-->
  <main style="margin-top: 58px;">
    <div class="container pt-4">
        {% block content %}

        {% endblock content %}
    </div>
  </main>
  <!--Main layout-->
</body>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.umd.min.js"
></script>
</html>

students/templates/students/edit.html
{% extends 'students/dashboard.html' %}

{% block content %}

<div class="container">
    <h1>Edit Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-info" type="submit">Save</button>
    </form>
</div>

{% endblock content %}

students/templates/students/guruhlarim.html
{% extends 'students/dashboard.html' %}

{% block content %}
<div class="container mt-5">
<table class="table ">
    <thead>
      <tr>
        <th scope="col"><b>ID</b></th>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{student.team.id}}</th>
        <td><a href="{% url 'students:lessons' student.team.id %}">{{student.team.name}}</a></td>
        <td>activ</td>
        
      </tr>
      
    </tbody>
  </table>
</div>
{% endblock content %}

students/templates/students/homedetail.html
{% extends 'students/dashboard.html' %}

{% block content %}
<div class="container mt-5">
<table class="table ">
    <thead>
      <tr>
        <th scope="col">Titel</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{homework.lesson.title}}</th>
        <td>{{homework.description}}</td>
        <td>{{homework.homework_file}}</td>
        
      </tr>
    </tbody>
  </table>
</div>
{% endblock content %}

students/templates/students/homework.html
{% extends 'students/dashboard.html' %}

{% block content %}
<h2>Homework for {{ lesson.title }}</h2>
<div class="container mt-5">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Titel</th>
          <th scope="col">Date</th>
          <th scope="col">File</th>
        </tr>
      </thead>
      <tbody>
        {% for lesson in lessons %}
          <tr>
            <th scope="row">{{ lesson.title }}</th>
            <td>{{ lesson.date }}</td>
            <td>
                {% if lesson.lesson_file %}
                <a href="{{ homework.lesson_file.url }}">{{homework.lesson_file}}</a>
                {% else %}
                No File
                {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  
<div class="container" style="background-color: rgb(216, 228, 228);">
    <h3 style="text-align:initial">Upload Homework</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-2">Upload</button>
    </form>
</div>
{% endblock content %}

students/templates/students/lessons.html
{% extends 'students/dashboard.html' %}

{% block content %}
<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Titel</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        <th scope="col">lesson file</th>
      </tr>
    </thead>
    <tbody>
      {% for lesson in lessons %}
        <tr>
          <th scope="row">{{ lesson.title }}</th>
          <td>{{ lesson.date }}</td>
          <td>
            {% if lesson.homework_status %}
            <a href="{% url 'students:homework_detail' lesson.id %}" class="btn btn-info">Bajarilgan</a>
              
            {% else %}
            <a href="{% url 'students:homework' lesson.id %}" class="btn btn-danger">Bajarilmagan</a>
            {% endif %}
          </td>
          <td>
            {% if lesson.lesson_file %}
            <a href="{{ lesson.lesson_file.url }}">{{lesson.lesson_file}}</a>
            {% else %}
            No File
            {% endif %}
        </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

students/templates/students/profil.html
{% extends 'students/dashboard.html' %}

{% block content %}
<section style="background-color: #eee;">
    <div class="container py-5">


      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="{{user.image.url}}" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{user.first_name}} {{user.last_name}}</h5>
              <p class="text-muted mb-1">{{user.jobs}}</p>
              <p class="text-muted mb-4">{{user.address}}</p>
              <div class="d-flex justify-content-center mb-2">
                <a href="{% url 'students:resed_password' %}"  class="btn btn-primary">Reset password</a>
                <a href="{% url 'students:edit' user.id %}" class="btn btn-outline-primary ms-1">Edit</a>
              </div>
            </div>
          </div>

        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone_number}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone_number}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.address}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

students/templates/students/reset_password.html
{% extends 'students/dashboard.html' %}

{% block content %}

<div class="container" >
<h1>Reset password page</h1>
<form  method="post" >
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-success mt-2">Login</button>
</form>
</div>

{% endblock content %}