config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import (
    StudentDashboardView, StudentGroupView, StudentLessonsView, 
    HomeworkView, HomeDetailView, ProfileView, EditProfileView, 
    ResetPasswordView,HomeworkListView
)

app_name = 'students'
urlpatterns = [
    path('dashboard/', StudentDashboardView.as_view(), name='dashboard'),
    path('groups/', StudentGroupView.as_view(), name='groups'),
    path('resed_password/', ResetPasswordView.as_view(), name='resed_password'),
    path('profil-students/', ProfileView.as_view(), name='profil'),
    path('lessons/<int:group_id>/', StudentLessonsView.as_view(), name='lessons'),
    path('homework/<int:lesson_id>/', HomeworkView.as_view(), name='homework'),
    path('edit/<int:id>/', EditProfileView.as_view(), name='edit'),
    path('homework-detail/<int:lesson_id>/', HomeDetailView.as_view(), name='homework_detail'),
    path('homeworks/<int:lesson_id>/', HomeworkListView.as_view(), name='homework_list'),
  ]

teachers/urls.py
from django.urls import path
from .views import  (TeacherView,TeacherTimesView,TeacherGroup,TeacherHomeworks,
                     TeacherStudentsView,ProfileView,EditProfileView,ResetPasswordView,
                     TeacherCreateLessonView,TeacherStudentLeson,DavomatListView)

app_name = 'teachers'


urlpatterns = [
    path('dashboard/',TeacherView.as_view(),name='dashboard'),
    path('guruhlarim/',TeacherTimesView.as_view(),name='guruhlarim'),
    path('resed_password/',ResetPasswordView.as_view(),name='resed_password'),
    path('profil-teacher/',ProfileView.as_view(),name='profil'),
    path('guruh/<int:team_id>/',TeacherGroup.as_view(),name='guruh'),
    path('homework/<int:team_id>/',TeacherHomeworks.as_view(),name='homeworks'),
    path('edit/<int:id>/',EditProfileView.as_view(),name='edit'),
    path('student/<int:team_id>/',TeacherStudentsView.as_view(),name='student'),
    path('create/<int:team_id>/',TeacherCreateLessonView.as_view(),name='create'),
    path('stydents/<int:id>/',TeacherStudentLeson.as_view(),name='stydents'),
    path('davomat/<int:id>/', DavomatListView.as_view(), name='davomat_list'),
]

users/urls.py
from django.urls import path
from .views import (LoginView, RegisterView,ProfileView,EditProfileView,Create,TeamStudentListView,
                    LogautView,GroupsView,StudentView,EditStudentView,Delete,StudentByTeam,
                    ResetPasswordView,AdminDashboardView,CreateTeamView,DeleteTeamView)

app_name = 'users'


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogautView.as_view(), name='logout'),
    path('create/', Create.as_view(), name='create'),
    path('profil/', ProfileView.as_view(), name='profil'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('edit/<int:id>/', EditProfileView.as_view(), name='edit'),
    path('group/', GroupsView.as_view(), name='groups'),
    path('students/', StudentView.as_view(), name='students'),
    path('get-by-students/<int:id>/', StudentByTeam.as_view(), name='students_by'),
    path('edit-student/<int:id>/', EditStudentView.as_view(), name='edit_student'),
    path('delete/<int:id>/', Delete.as_view(), name='delete'),
    path('resed-password', ResetPasswordView.as_view(), name='resed_password'),
    path('create-team/', CreateTeamView.as_view(), name='create_team'),
    path('delete-team/<int:id>/', DeleteTeamView.as_view(), name='delete_team'),
    path('team/student/create/', TeamStudentListView.as_view(), name='create_student'),
]

students/models.py
from django.db import models
from users.models import Team,Student,Teacher
from django.core.validators import MaxValueValidator,FileExtensionValidator

class Lesson(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='lesson')
    title = models.CharField(max_length=100, unique=True)
    date = models.DateField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    homework_status = models.BooleanField(default=False)
    lesson_file = models.FileField(upload_to='lesson/',  null=True,blank=True)
    video = models.FileField(
        upload_to='video/', 
        validators=[FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'AVI', 'WMV'])],
        null=True,
        blank=True
    )


    class Meta:
        unique_together = ['team', 'title']

    def __str__(self):
        return self.title


class Homework(models.Model):
    lesson = models.OneToOneField(Lesson, on_delete=models.CASCADE, related_name='homework')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, related_name='homeworks')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='students')
    description = models.TextField()
    homework_file = models.FileField(upload_to='homeworks', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)


    class Meta:
        unique_together = ['student', 'team']

    def __str__(self):
        return f"{self.student.user.first_name}-- {self.lesson.title}"

class Davomat(models.Model):
    team = models.ForeignKey(Team,on_delete=models.CASCADE,related_name='team',null=True,blank=True)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.student} --> ,{self.data} --> {'Present' if self.status else 'Absent'}"
    

students/forms.py
from django import forms
from .models import Homework,Davomat

class HomeworkForm(forms.Form):
    description = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))
    homework_file = forms.FileField(widget=forms.FileInput())


class DavomatForm(forms.ModelForm):
    class Meta:
        model = Davomat
        fields = ['team', 'student', 'status'] 
        widgets = {
            'team': forms.Select(attrs={'class': 'form-control'}),
            'student': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

teachers/forms.py
from django import forms
from students.models import Davomat ,Lesson

class CreateLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = [ 'title', 'homework_status', 'lesson_file']
    
    title = forms.CharField(widget=forms.TextInput({'class': 'form-control'}))

class DavomatForm(forms.ModelForm):
    class Meta:
        model = Davomat
        fields = [ 'student', 'status'] 
        widgets = {
            'student': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from users.permissionmixin import StudentRequiredMixin
from django.views import View
from users.models import Student, Team,User
from .forms import HomeworkForm,DavomatForm
from .models import Lesson, Homework,Davomat
from users.forms import ProfileForm,ResetPasswordForm

class StudentDashboardView(StudentRequiredMixin, View):
    def get(self, request):
        return render(request, 'students/dashboard.html')

class StudentGroupView(StudentRequiredMixin, View):
    def get(self, request):
        student = Student.objects.get(user=request.user)
        return render(request, 'students/guruhlarim.html', context={"student":student})
    
class HomeworkListView(View):
    def get(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        homeworks = Homework.objects.filter(lesson=lesson)
        return render(request, 'students/homework.html', {'lesson': lesson, 'homeworks': homeworks})

class StudentLessonsView(StudentRequiredMixin, View):
    def get(self, request, group_id):
        team = get_object_or_404(Team, id=group_id)
        lessons = team.lesson.all()
        return render(request, 'students/lessons.html', context={"lessons":lessons})
    

class HomeworkView(StudentRequiredMixin, View):
    def get(self, request, lesson_id):
        form = HomeworkForm()
        return render(request, 'students/homework.html', context={"form":form})
    
    def post(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        student = get_object_or_404(Student, user=request.user)

        form = HomeworkForm(request.POST, request.FILES)
        if form.is_valid():
            homework = Homework()
            homework.lesson = lesson
            homework.student = student
            homework.description = form.cleaned_data['description']
            homework.homework_file = form.cleaned_data['homework_file']
            homework.save()

            lesson.homework_status = True
            lesson.save()

            return redirect('students:dashboard')
        form = HomeworkForm()
        return render(request, 'students/homework.html', context={"form":form})
        
class HomeDetailView(StudentRequiredMixin,View):
    def get(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        student = get_object_or_404(Student , user=request.user)
        homework = Homework.objects.filter(lesson=lesson , student=student).first()
        return render(request,'students/homedetail.html',{'homework':homework})
    
class ProfileView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        return render(request,'students/profil.html',context={"user":user})


class EditProfileView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(instance=user)
        return render(request, 'students/edit.html', {'form': form})

    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('students:profil')  
        return render(request, 'students/edit.html', {'form': form})

class ResetPasswordView(LoginRequiredMixin,View):
    def get(self, request):
        form = ResetPasswordForm()
        return render(request, 'students/reset_password.html', {'form':form})

    def post(self, request):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            user = request.user
            user.set_password(new_password)
            user.save()
            return redirect('/')
        form = ResetPasswordForm()
        return render(request, 'students/reset_password.html', {'form':form})
    
class DavomatListView(View):
    def get(self, request):
        davomat_list = Davomat.objects.all()
        form = DavomatForm()
        return render(request, 'students/davomat_list.html', {'davomat_list': davomat_list, 'form': form})

    def post(self, request):
        form = DavomatForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('davomat_list')
        davomat_list = Davomat.objects.all()
        return render(request, 'students/davomat_list.html', {'davomat_list': davomat_list, 'form': form})

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,get_object_or_404,redirect
from  users.permissionmixin import TeacherRequiredMixin
from  django.views import  View
from  users.models import Teacher,Student,User
from  students.models import Lesson,Team,Homework,Davomat
from users.forms import ProfileForm,ResetPasswordForm
from .forms import CreateLessonForm,DavomatForm
from django.urls import reverse


class TeacherView(TeacherRequiredMixin,View):
    def get(self,request):
        return render(request,'teachers/dashboard.html')

class TeacherTimesView(TeacherRequiredMixin,View):
    def get(self,request):
        teacher = get_object_or_404(Teacher,user=request.user)
        teams = teacher.teacher.all()
        return render(request,'teachers/guruhlarim.html',{"teams":teams})

class TeacherGroup(TeacherRequiredMixin,View):
    def get(self,request,team_id):
        team = get_object_or_404(Team,id=team_id)
        lessons = team.lesson.all()
        return render(request,'teachers/guruh.html',{'team':team,'lessons':lessons})

class TeacherHomeworks(TeacherRequiredMixin,View):
    def get(self,request,team_id):
        team = get_object_or_404(Team,id=team_id)
        lessons = team.homeworks.all()
        return render(request,'teachers/guruh.html',{'team':team,'lessons':lessons})

class TeacherStudentsView(TeacherRequiredMixin,View):
    def get(self,request,team_id):
        team = get_object_or_404(Team,id=team_id)
        student = team.students.all()
        return render(request,'teachers/student.html',{'team':team,'student':student})

class ProfileView(LoginRequiredMixin,View):
    def get(self,request):
        user = request.user
        return render(request,'teachers/profil.html',context={"user":user})

class TeacherHomevorkStudent(TeacherRequiredMixin,View):
    def get(self,request,team_id):
        team = get_object_or_404(Team,id=team_id)
        lessons = team.lesson.all()
        return render(request,'teachers/guruh.html',{'team':team,'lessons':lessons})

class EditProfileView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(instance=user)
        return render(request, 'teachers/edit.html', {'form': form})

    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('teachers:profil')  
        return render(request, 'teachers/edit.html', {'form': form})

class ResetPasswordView(LoginRequiredMixin,View):
    def get(self, request):
        form = ResetPasswordForm()
        return render(request, 'teachers/reset_password.html', {'form':form})

    def post(self, request):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            user = request.user
            user.set_password(new_password)
            user.save()
            return redirect('/')
        form = ResetPasswordForm()
        return render(request, 'teachers/reset_password.html', {'form':form})


class TeacherCreateLessonView(TeacherRequiredMixin, View):
    def get(self, request, team_id):
        form = CreateLessonForm()
        return render(request, 'teachers/create_lesson.html', {'form': form})

    def post(self, request, team_id):
        team = get_object_or_404(Team, id=team_id)
        form = CreateLessonForm(request.POST, request.FILES)
        if form.is_valid():
            lesson = Lesson(
                team=team,
                title=form.cleaned_data['title'],
                lesson_file=form.cleaned_data['lesson_file'],
            )
            lesson.save()
            url = reverse('teachers:homeworks', args=[team_id])
            return redirect(url)
        return render(request, 'teachers/create_lesson.html', {'form': form})


class TeacherStudentLeson(TeacherRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        lesson_id = kwargs.get('id')  
        lesson = get_object_or_404(Lesson, id=lesson_id)
        homeworks = Homework.objects.filter(lesson=lesson).select_related('student', 'team')
        return render(request, 'teachers/students.html', {'homeworks': homeworks, 'lesson': lesson})

class TeacherHomeworkListView(TeacherRequiredMixin, View):
    def get(self, request):
        lessons = Lesson.objects.filter(team__teacher=request.user.teacher)
        homeworks = Homework.objects.filter(lesson__in=lessons).select_related('student__user', 'lesson')
        return render(request, 'teachers/homework_list.html', {'homeworks': homeworks})




class DavomatListView(View):
    def get(self, request, id):
        team = get_object_or_404(Team, id=id)
        students = team.students.all()
        davomat_records = Davomat.objects.filter(team=team)
        
        # Create a dictionary to easily access attendance status per student
        student_attendance = {
            student.id: {
                'name': student.user.first_name,
                'status': next((d.status for d in davomat_records if d.student == student), False)
            }
            for student in students
        }
        
        form = DavomatForm()
        return render(request, 'teachers/davomat_list.html', {
            'students': students,
            'team': team,
            'student_attendance': student_attendance,
            'form': form
        })

    def post(self, request, id):
        team = get_object_or_404(Team, id=id)
        students = team.students.all()

        # Process attendance for each student
        for student in students:
            status = request.POST.get(f'status_{student.id}', 'off') == 'on'
            Davomat.objects.update_or_create(
                team=team,
                student=student,
                defaults={'status': status}
            )

        messages.success(request, "Attendance saved successfully.")
        return redirect('teachers:student')   

teachers/templates/teachers/create_lesson.html
{% extends 'teachers/dashboard.html' %}

{% block content %}

<div class="container" style="background-color: rgb(236, 236, 211);">

    <form  method="post" >
        {% csrf_token %}

        {{form}}

        <button type="submit" class="btn btn-success mt-2">Save</button>
    </form>
    </div>

{% endblock content %}

teachers/templates/teachers/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Offline Teacher Panel</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="icon" href="{% static 'icon/talim.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"  
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.min.css"
    rel="stylesheet"
    />
</head>
<body style="background-color: rgb(237, 243, 245)">
    <!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="background-color:rgb(240, 230, 200)">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
                <a
                    href="{% url 'teachers:dashboard' %}"
                    class="list-group-item list-group-item-action py-2 ripple"
                    aria-current="true"
                >
                    <i class="fas fa-globe fa-fw me-3"></i><span>Bosh sahifa</span>
                </a>


            <a href="{% url 'teachers:guruhlarim' %}" class="list-group-item list-group-item-action py-3 ripple"
            ><i class="fas fa-users fa-fw me-4"></i><span>Guruhlarim</span></a
          >


          <a href="{% url 'teachers:profil' %}" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-bar fa-fw me-3"></i><span>Sozlamalar</span></a
          >
        </div>
      </div>
    </nav>
    <!-- Sidebar -->

    <!-- Navbar -->
    <nav  id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid " >
        <!-- Toggle button -->
        <button data-mdb-button-init
          class="navbar-toggler"
          type="button"
          data-mdb-collapse-init
          data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>

        <!-- Brand -->
        <a class="navbar-brand" href="#">
        <img
          src="{% static 'icon/ummat.jpg' %}"
          height="50"
          alt="Ummat ta`lim Logo"
          loading="lazy"
        />
        </a>
      </a>

        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">
            <!-- Avatar -->
          <li class="nav-item dropdown" style="background-color: rgb(250, 248, 246);">
            <a
              data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="{{user.image.url}}"
                class="rounded-circle"
                height="22"
                alt="Avatar"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <li>
                <a class="dropdown-item" href="{% url 'users:profil' %}">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->

  <!--Main layout-->
  <main style="margin-top: 58px;">
    <div class="container pt-4">
        {% block content %}

        {% endblock content %}
    </div>
  </main>
  <!--Main layout-->
</body>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.0/mdb.umd.min.js"
></script>
</html>

teachers/templates/teachers/edit.html
{% extends 'teachers/dashboard.html' %}

{% block content %}

<div class="container">
    <h1>Edit Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-info" type="submit">Save</button>
    </form>
</div>

{% endblock content %}

teachers/templates/teachers/guruh.html
{% extends 'teachers/dashboard.html' %}

{% block content %}
<div class="mt-5">
  <h4>{{ team.name }} </h4>
</div>
<br>
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teachers:guruh' team.id %}">Darslar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teachers:student' team.id %}">O'quvchilar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teachers:davomat_list' team.id %}">Yoqlama</a>
        </li>
      </ul>
      <ul class="nav-item">
          <a class="btn btn-outline-success" href="{% url 'teachers:create' team.id %}">Create Lesson</a>
        
      </ul>
    </div>

  </div>
</nav>
<br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Date</th>
            <th scope="col">Homework Status</th>
            <th scope="col">lesson file</th>

        </tr>
    </thead>
    <tbody>
        {% for lesson in lessons %}
        <tr class="table-info">
            <td>
                <a href="{% url 'teachers:stydents' lesson.id %}">{{ lesson.title }}</a>
            </td>
            <td>{{ lesson.date }}</td>
            <td>{{ lesson.homework_status|yesno:"Active,Inactive" }}</td>
            <td>
              {% if lesson.lesson_file %}
              <a href="{{ lesson.lesson_file.url }}">{{lesson.lesson_file}}</a>
              {% else %}
              No File
              {% endif %}
          </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

teachers/templates/teachers/guruhlarim.html
{% extends 'teachers/dashboard.html' %}

{% block content %}
<div class="container mt-5">
<table class="table ">
    <thead>
      <tr>
        <th scope="col"><b>ID</b></th>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
    {% for i in teams %}
      <tr>
        <th scope="row"><a href="{% url 'teachers:guruh' i.id %}">{{i.name}}</a></th>
        <td>{{i.date_created}}</td>
        <td>activ</td>

      </tr>
    {% endfor %}

    </tbody>
  </table>
</div>
{% endblock content %}

teachers/templates/teachers/homework.html
{% extends 'teachers/dashboard.html' %}

{% block content %}
<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Titel</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ lesson.title }}</th>
        <td>{{ lesson.date }}</td>
        <td>
          {% if lesson.homework_status %}
            <a href="{% url 'students:homework_detail' lesson.id %}" class="btn btn-info">Bajarilgan</a>
          {% else %}
            <a href="{% url 'students:homework' lesson.id %}" class="btn btn-danger">Bajarilmagan</a>
          {% endif %}
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock content %}

teachers/templates/teachers/homeworkcheck_form.html
{% extends 'teachers/dashboard.html' %}

{% block content %}
<div class="mt-5">
  <h4>Review and Grade Homework Submission</h4>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock content %}

teachers/templates/teachers/profil.html
{% extends 'teachers/dashboard.html' %}

{% block content %}
<section style="background-color: #eee;">
    <div class="container py-5">


      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="{{user.image.url}}" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{user.first_name}} {{user.last_name}}</h5>
              <p class="text-muted mb-1">{{user.jobs}}</p>
              <p class="text-muted mb-4">{{user.address}}</p>
              <div class="d-flex justify-content-center mb-2">
                <a href="{% url 'teachers:resed_password' %}"  class="btn btn-primary">Reset password</a>
                <a href="{% url 'teachers:edit' user.id %}" class="btn btn-outline-primary ms-1">Edit</a>
              </div>
            </div>
          </div>

        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone_number}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.phone_number}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.address}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}